CREATE DATABASE grocery_db;
USE grocery_db;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

SELECT * FROM supplier;
-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);
SELECT * FROM categories;

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

SELECT * FROM employees;

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

SELECT * FROM customers;

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

SELECT * FROM products;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

SELECT * FROM orders;

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);


SELECT * FROM order_details;

SELECT * FROM customers;

-- Customer Insights ----------------------------------------------

-- 1
SELECT COUNT(DISTINCT cust_id) AS unique_cust
FROM orders;


-- SELECT o.ord_id,
--        o.cust_id
-- FROM orders as o      
-- JOIN customers as c
-- ON c.cust_id = o.cust_id;


-- 2. Which customers have placed the highest number of orders?
SELECT
    cust_id,
    COUNT(ord_id) AS total_orders
FROM orders
GROUP BY cust_id
ORDER BY total_orders DESC;

-- 3. What is the total and average purchase value per customer?
SELECT c.cust_id,
       c.cust_name,
       SUM(od.total_price) AS total_purchase,
       AVG(od.total_price) AS avg_purchase
FROM customers c
JOIN orders o
ON c.cust_id = o.cust_id
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name;
	   
       
-- 4. Who are the top 5 customers by total purchase amount?

SELECT c.cust_id,
       c.cust_name,
       SUM(od.total_price) AS total_purchase
FROM customers c
JOIN orders o
ON c.cust_id = o.cust_id
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase DESC
LIMIT 5;


-- 2. Product Performance ---------------------------------

-- 1. How many products exist in each category?
SELECT cat_id,
       COUNT(prod_id)
FROM products
GROUP BY cat_id;

-- 2. What is the average price of products by category?

SELECT cat_id,
       AVG(prod_id) AS average_price_of_products
FROM products
GROUP BY cat_id;       

-- 3. Which products have the highest total sales volume (by quantity)?

SELECT
    p.prod_name,
    SUM(od.quantity) AS total_sales_volume
FROM products p
JOIN order_details od
ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_sales_volume DESC;   

-- 4. What is the total revenue generated by each product?

SELECT p.prod_id,
	   SUM(od.total_price) AS total_revenue
FROM products as p
JOIN order_details as od
ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name;       


-- 5. How do product sales vary by category and supplier?

SELECT
    c.cat_name,
    s.sup_name,
    SUM(od.total_price) AS total_sales
FROM products p
JOIN categories c
ON p.cat_id = c.cat_id
JOIN supplier s
ON p.sup_id = s.sup_id
JOIN order_details od
ON p.prod_id = od.prod_id
GROUP BY c.cat_id, c.cat_name,
         s.sup_id, s.sup_name
ORDER BY total_sales DESC;


-- 3. Sales and Order Trends ----------------------------------

-- 1. How many orders have been placed in total?

SELECT COUNT(ord_id) AS total_orders
FROM order_details;

-- 2. What is the average value per order?

SELECT AVG(order_total) AS average_order_value
FROM (
    SELECT
        ord_id,
        SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) AS temp;

-- 3. On which dates were the most orders placed?

SELECT
    order_date,
    COUNT(ord_id) AS total_orders
FROM orders
GROUP BY order_date
HAVING COUNT(ord_id) = (
    SELECT MAX(order_count)
    FROM (
        SELECT COUNT(*) AS order_count
        FROM orders
        GROUP BY order_date
    ) AS temp
);

-- 4. What are the monthly trends in order volume and revenue?

-- SELECT order_date
-- FROM orders
-- LIMIT 10;

-- SELECT
--     order_date,
--     STR_TO_DATE(order_date, '%m/%d/%Y') AS converted_date
-- FROM orders
-- LIMIT 10;


SELECT
    YEAR(STR_TO_DATE(o.order_date, '%m/%d/%Y')) AS year,
    MONTH(STR_TO_DATE(o.order_date, '%m/%d/%Y')) AS month,
    COUNT(DISTINCT o.ord_id) AS order_volume,
    SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY
    YEAR(STR_TO_DATE(o.order_date, '%m/%d/%Y')),
    MONTH(STR_TO_DATE(o.order_date, '%m/%d/%Y'))
ORDER BY year, month;

-- 5. How do order patterns vary across weekdays and weekends?

SELECT
    CASE
        WHEN DAYOFWEEK(STR_TO_DATE(order_date, '%m/%d/%Y')) IN (1, 7)
        THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(ord_id) AS total_orders
FROM orders
GROUP BY day_type;


-- 4. Supplier Contribution -------------------------- 

-- 1. How many suppliers are there in the database? 

SELECT COUNT(sup_id) AS total_suppliers FROM supplier;

-- 2. Which supplier provides the most products?

SELECT
    s.sup_id,
    s.sup_name,
    COUNT(p.prod_id) AS total_products
FROM supplier s
JOIN products p
ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_products DESC
LIMIT 1;
       
 -- 3. What is the average price of products from each supplier?
 
 SELECT
    s.sup_id,
    s.sup_name,
    AVG(p.price) AS avg_product_price
FROM supplier s
JOIN products p
ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name;

-- 4. Which suppliers contribute the most to total product sales (by revenue)?

SELECT
    s.sup_id,
    s.sup_name,
    SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p
ON s.sup_id = p.sup_id
JOIN order_details od
ON p.prod_id = od.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_revenue DESC;

-- 5. Employee Performance

-- 1. How many employees have processed orders

SELECT COUNT(DISTINCT emp_id) AS employees_processed_orders
FROM orders;

-- 2. Which employees have handled the most orders?

SELECT
    e.emp_id,
    e.emp_name,
    COUNT(o.ord_id) AS total_orders
FROM employees e
JOIN orders o
ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_orders DESC;

-- 3. What is the total sales value processed by each employee?

SELECT
    e.emp_id,
    e.emp_name,
    SUM(od.total_price) AS total_sales_value
FROM employees e
JOIN orders o
ON e.emp_id = o.emp_id
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_sales_value DESC;


-- 4. What is the average order value handled per employee?

SELECT
    e.emp_id,
    e.emp_name,
    AVG(order_total) AS avg_order_value
FROM employees e
JOIN orders o
ON e.emp_id = o.emp_id
JOIN (
    SELECT
        ord_id,
        SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) od
ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY avg_order_value DESC;


-- 6. Order Details Deep Dive

-- 1. What is the relationship between quantity ordered and total price?

SELECT
    quantity,
    AVG(total_price) AS avg_total_price
FROM order_details
GROUP BY quantity
ORDER BY quantity;


-- 2. What is the average quantity ordered per product?

SELECT
    p.prod_id,
    p.prod_name,
    AVG(od.quantity) AS avg_quantity_ordered
FROM products p
JOIN order_details od
ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_quantity_ordered DESC;

-- 3. How does the unit price vary across products and orders?

SELECT
    p.prod_name,
    AVG(od.each_price) AS avg_unit_price,
    MIN(od.each_price) AS min_price,
    MAX(od.each_price) AS max_price
FROM products p
JOIN order_details od
ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_unit_price DESC; 
